import { StyleSheet } from 'react-native';
import { darkTheme } from '../../../theme/colors';

const GameDetailsStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: darkTheme.bg,
  },
  glowPurple: {
    position: 'absolute',
    top: -80,
    right: -80,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: darkTheme.glowPurple,
    opacity: 0.55,
  },
  glowCyan: {
    position: 'absolute',
    bottom: 120,
    left: -100,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: darkTheme.glowCyan,
    opacity: 0.35,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  containerGameDetails: {
    flex: 1,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 8,
    width: '100%',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: darkTheme.bgCard,
    borderWidth: 1,
    borderColor: darkTheme.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  containerCoverImage: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 12,
  },
  coverImage: {
    width: 200,
    height: 200,
    borderRadius: 20,
  },
  containerGameInformation: {
    width: '100%',
    borderRadius: 24,
    backgroundColor: darkTheme.bgCard,
    borderWidth: 1,
    borderColor: darkTheme.border,
    padding: 24,
    marginTop: 8,
  },
  gameTile: {
    color: darkTheme.textPrimary,
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'Inter-VariableFont_opsz,wght',
    textAlign: 'left',
    marginBottom: 16,
  },
  statPillsRow: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  statPill: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    paddingVertical: 14,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  statPillLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.5)',
    fontFamily: 'Inter-VariableFont_opsz,wght',
    marginBottom: 4,
  },
  statPillValue: {
    fontSize: 22,
    fontWeight: '700',
    fontFamily: 'Inter-VariableFont_opsz,wght',
  },
  gameDescription: {
    color: darkTheme.textSecondary,
    fontSize: 14,
    marginBottom: 20,
    lineHeight: 20,
    fontFamily: 'Inter-VariableFont_opsz,wght',
  },
  playGameButton: {
    backgroundColor: darkTheme.purple,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 14,
    alignSelf: 'flex-start',
  },
  playGameButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Inter-VariableFont_opsz,wght',
  },
  rotateHint: {
    position: 'absolute',
    bottom: 40,
    left: 20,
    right: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 20,
  },
  rotateHintIcon: {
    fontSize: 24,
    marginRight: 10,
  },
  rotateHintText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    fontFamily: 'Inter-VariableFont_opsz,wght',
  },
});

export default GameDetailsStyles;
